// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZg9WUKqxNohw21EQC45OIQBxPjDh7l6c',
    appId: '1:868885403562:web:765127e31006ea3a06bdd3',
    messagingSenderId: '868885403562',
    projectId: 'agenda-caa11',
    authDomain: 'agenda-caa11.firebaseapp.com',
    storageBucket: 'agenda-caa11.appspot.com',
    measurementId: 'G-7X6ZKNKJ23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGSlnEpXMm_NtywOWfGEzLrSQlHIWsmKs',
    appId: '1:868885403562:android:c3407ea39e69d88b06bdd3',
    messagingSenderId: '868885403562',
    projectId: 'agenda-caa11',
    storageBucket: 'agenda-caa11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVbaKhohZEbvX1-kKEdjTcfZQHGvsLITI',
    appId: '1:868885403562:ios:ae55657afdd0c8fe06bdd3',
    messagingSenderId: '868885403562',
    projectId: 'agenda-caa11',
    storageBucket: 'agenda-caa11.appspot.com',
    iosClientId: '868885403562-4qf4ukpdet22atcra0ni20upr4k3an1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );
}
